version: '3.6'
services:
  iris:
    container_name: "IRIS"
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --ISCAgent false
    ports: 
      - 1972
      - 52773
      - 53773
    volumes:
      - ./:/irisrun/repo
