Class RestDocumentation.RouteDocumentaion Extends %RegisteredObject
{

Property Url As %String;

Property Method As %String;

Property Call As %String;

Property Cors As %String;

Property Description As %String;

Property ResponseBody As %Dictionary.ClassDefinition;

Property RequestBody As %Dictionary.ClassDefinition;

Property TypeAplication As %String;

Property ParameterQuery As list Of %String;

}
